---
- hosts: microk8s_WORKERS

  become: yes
  become_user: root
  tasks:
    - name: "Run Worker commands"
      command: "sudo microk8s join 192.168.110.183:25000/540490f08ad342a2fd507fa4e4c9e274/41a79cfbd8ef --worker"
