---
- hosts: microk8s_WORKERS

  become: yes
  become_user: root
  tasks:
    - name: "Run Worker commands"
      shall: sudo microk8s join 192.168.110.117:25000/f6ed6f187b6f0d2aa4086d5c0dd803c2/86dc4a578ea5 --worker
