---
- hosts: all

  become: yes
  become_user: root
  tasks:
    - name: update apt packages
      apt:
        upgrade: yes
        update_cache: yes
    - name: Update apt and install prerequisites
      apt:
        name:
          - microk8s
        state: latest
        update_cache: yes
