---
- hosts: microk8s_WORKERS

  become: yes
  become_user: root
  tasks:
    - name: "Run Worker commands"
      command: "sudo microk8s join 192.168.110.117:25000/b4c5baf4279a1f7b1f52551aa24f6dde/86dc4a578ea5 --worker"
