- hosts: all
  become: yes
  become_user: root
  roles:
    - role: 'virtualwhl.microk8s'
      vars:
        microk8s_plugins:
          dns: "8.8.8.8"
          ingress: true
          metrics-server: false
          cert-manager: true
          openebs: true       
          portainer: true
          helm3: true
